import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "@/components/BottomNav";
import RequestModal from "@/components/RequestModal";
import ClientProviders from "@/components/ClientProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${geistSans.variable} 
        ${geistMono.variable} 
        antialiased
        bg-stone-50 
        min-h-screen
        relative`}
      >
        <ClientProviders>
        {children}
        <BottomNav />
        <RequestModal />
      </ClientProviders>
      </body>
    </html>
  );
}
